### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by PythonLinks** [whaleygeek/pyforth#1]
First thank you for what looks like a very nice piece of software.  It has a lot of richness to hit.  I did a quick comparison of the 3 Forths could find written in Python, and this one won. 
https://pythonlinks.info/forth
Maybe I will add that table to the readme in my first pull request. 

So I did a git clone, and ran the tests.  4 tests failed. I attached the error log to the end of this page.   I think that I will take a look and try to fix them.   Good to read other peoples code.  What I really liked is that you did not just implement each function, you actually used a table to look up the appropriate Python function.  Very elegantly done. 
Meta information is so powerful. 

The error message is appended. 
Thanks 
Chris

 python tests.py
tests.py:151: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals("*", self.f.outs.get())
.E......E......................EE...
======================================================================
ERROR: test_02_hello (__main__.TestForth)
Output a Hello world! message
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 157, in test_02_hello
    self.f.execute_word("TEST")
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 2129, in execute_word
    self.machine.call(exec_cf)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1400, in call
    self.mem.call(addr)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 218, in call
    handler.call(addr-start)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1296, in call
    execfn()
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1878, in n_execute
    self.call(cf)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1400, in call
    self.mem.call(addr)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 218, in call
    handler.call(addr-start)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1296, in call
    execfn()
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1916, in n_dodoes
    self.call(cf) # if this called n_exit, we must now exit this level of the dodoes loop.
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1400, in call
    self.mem.call(addr)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 218, in call
    handler.call(addr-start)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1296, in call
    execfn()
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1959, in n_dostr
    self.rs.pushn(ip)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 595, in pushn
    b0, b1 = Number.to_bytes(number)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 62, in to_bytes
    b0 = (n & 0xFF00)>>8
TypeError: unsupported operand type(s) for &: 'float' and 'int'

======================================================================
ERROR: test_09_div (__main__.TestForth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 194, in test_09_div
    self.f.execute_word("TEST")
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 2129, in execute_word
    self.machine.call(exec_cf)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1400, in call
    self.mem.call(addr)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 218, in call
    handler.call(addr-start)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1296, in call
    execfn()
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1878, in n_execute
    self.call(cf)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1400, in call
    self.mem.call(addr)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 218, in call
    handler.call(addr-start)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1296, in call
    execfn()
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1916, in n_dodoes
    self.call(cf) # if this called n_exit, we must now exit this level of the dodoes loop.
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1400, in call
    self.mem.call(addr)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 218, in call
    handler.call(addr-start)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1296, in call
    execfn()
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1600, in n_div
    self.ds.pushn(r)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 595, in pushn
    b0, b1 = Number.to_bytes(number)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 62, in to_bytes
    b0 = (n & 0xFF00)>>8
TypeError: unsupported operand type(s) for &: 'float' and 'int'

======================================================================
ERROR: test_find (__main__.TestForth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 476, in test_find
    self.f.execute_word("TEST")
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 2129, in execute_word
    self.machine.call(exec_cf)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1400, in call
    self.mem.call(addr)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 218, in call
    handler.call(addr-start)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1296, in call
    execfn()
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1878, in n_execute
    self.call(cf)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1400, in call
    self.mem.call(addr)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 218, in call
    handler.call(addr-start)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1296, in call
    execfn()
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1916, in n_dodoes
    self.call(cf) # if this called n_exit, we must now exit this level of the dodoes loop.
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1400, in call
    self.mem.call(addr)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 218, in call
    handler.call(addr-start)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1296, in call
    execfn()
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1959, in n_dostr
    self.rs.pushn(ip)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 595, in pushn
    b0, b1 = Number.to_bytes(number)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 62, in to_bytes
    b0 = (n & 0xFF00)>>8
TypeError: unsupported operand type(s) for &: 'float' and 'int'

======================================================================
ERROR: test_number (__main__.TestForth)
Test various NUMBER parsing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 508, in test_number
    self.f.execute_word("T0")
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 2129, in execute_word
    self.machine.call(exec_cf)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1400, in call
    self.mem.call(addr)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 218, in call
    handler.call(addr-start)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1296, in call
    execfn()
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1878, in n_execute
    self.call(cf)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1400, in call
    self.mem.call(addr)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 218, in call
    handler.call(addr-start)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1296, in call
    execfn()
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1916, in n_dodoes
    self.call(cf) # if this called n_exit, we must now exit this level of the dodoes loop.
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1400, in call
    self.mem.call(addr)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 218, in call
    handler.call(addr-start)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1296, in call
    execfn()
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 1959, in n_dostr
    self.rs.pushn(ip)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 595, in pushn
    b0, b1 = Number.to_bytes(number)
  File "/home/lozinski/code/cromlech/pyforth/src/forth.py", line 62, in to_bytes
    b0 = (n & 0xFF00)>>8
TypeError: unsupported operand type(s) for &: 'float' and 'int'

----------------------------------------------------------------------
Ran 36 tests in 10.319s

FAILED (errors=4)
(pl2) ~/code/cromlech/pyforth/src$

**Comment by whaleygeek** [comment]
Thanks for the info and leader board, and thanks for the test log, I will look into those!

This was a christmas project a few years ago, I was reading the Brodie book and looking for a way to test out things to improve my understanding, and using Python seemed a nice way to do it, to bring all that alive

I have an obsession about 'what is the smallest core language you can write, before you can start writing that language in itself'.

I have also looked at BCPL with it's intcode, LISP, Lua, and some small C compilers. This was the only one that I wrote some real code for, and had a lot of fun learning about FORTH in the process.

I may pick this project up again in the future, and the first thing I will do is make sure it is Python 3 safe and fix the tests, so thanks very much for the test log!

David.

**Comment by PythonLinks** [comment]
> On Mar 13, 2020, at 7:15 PM, David Whale <notifications@github.com> wrote:
> 
> I have an obsession about 'what is the smallest core language you can write, before you can start writing that language in itself’.


My interest lies in what is the smallest cpu one can build.  Then we can have lots of them 
on a cpu.   Small language on a small cpu.  

Green arrays does 144. 
http://www.greenarraychips.com/ <http://www.greenarraychips.com/>

But they do not have enough memory.  
So now I am looking at the H2 cpu.

https://github.com/howerj/forth-cpu <https://github.com/howerj/forth-cpu>

Beautifully documented.  Unlike the J1, it has an interrupt.  Not quite as drastically scaled down. 
The H2 has both a virtual cpu in C, and a board emulator in C.  Perfect. 

But first I need to learn Forth, may as well find one written in Python.  Then it is easy to 
understand and change.  

Warm Regards
Christopher Lozinski

https://PythonLinks.info
tel: +48 32 361 3136
Skype: clozinski
